# Generated by Django 4.2.30 on 2026-06-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadrilla',
            name='supervisor',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
