# Generated by Django 4.2.30 on 2026-07-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_cuadrilla_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsolicitud',
            name='estado_entrega',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('alistado', 'Alistado'), ('entregado', 'Entregado'), ('cerrado', 'Cerrado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('aprobada', 'Aprobada'), ('alistado', 'Alistado — Listo para recoger'), ('en_entrega', 'Pendiente de Entrega'), ('entregada', 'Entregada Totalmente'), ('parcial', 'Entregada Parcialmente'), ('cerrada', 'Cerrada')], default='pendiente', max_length=20),
        ),
    ]
