# Generated by Django 4.2.30 on 2026-07-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0003_alter_itemsolicitud_estado_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='oculto_almacen',
            field=models.BooleanField(default=False),
        ),
    ]
